### ISSUE TITLE
小队的屏蔽词颜色不会改变

### ISSUE THREAD

**Issue by Yellabble** [Loskh/StarlightBreaker#1]

**Comment by Yellabble** [comment]
![QQ图片20210807132346](https://user-images.githubusercontent.com/54705436/128589104-1851dc62-eb6e-43a4-ab97-2d14f12dfbeb.png)

**Comment by Loskh** [comment]
https://github.com/PrototypeSeiren/StarlightBreaker/blob/2c4c0320d1a278af4522267a2f1b8514c45fb05f/StarlightBreaker.Dalamud/Plugin.cs#L154
Fixed
