### ISSUE TITLE
小队内其他人发的屏蔽词 颜色不会替换。

### ISSUE THREAD

**Issue by Yellabble** [Loskh/StarlightBreaker#2]
![QQ图片20210814003529](https://user-images.githubusercontent.com/54705436/129391308-ca2afde4-ffc8-4d1f-8f21-a147dfe87919.png)

**Comment by Loskh** [comment]
是的，就是这样设计的
颜色是为了避免你和别人交流的时候，因为你不知道自己发出来的是*，从而造成的不便
所以没必要替换别人发送屏蔽词的颜色，因为不会影响正常交流

**Comment by Yellabble** [comment]
噢噢好的，不知道之后能不能出一个选项就是能把所有人的屏蔽词都标注出颜色。
还有就是招募板上的屏蔽词会不会加颜色标注

**Comment by Loskh** [comment]
这个功能可以作为可选，以后再说（

**Comment by Yellabble** [comment]
今天发现更新了，感谢更新！
