### ISSUE TITLE
请问目前还有不使用ACT的方法吗？

### ISSUE THREAD

**Issue by christaikobo** [Loskh/StarlightBreaker#6]
6.0客户端没找到SoundCoreBridge.dll的位置啊

**Comment by Loskh** [comment]
暂时是没了

**Comment by Loskh** [comment]
更新了一个删除屏蔽词库的mod,可以试试

**Comment by christaikobo** [comment]
感谢，我试试！

**Comment by christaikobo** [comment]
回报：的确有效
感谢！

**Comment by christaikobo** [comment]
回报：
经常发生崩溃，需要初始化后重新启用
最近一次反复初始化后还是不能用

**Comment by Loskh** [comment]
> 回报： 经常发生崩溃，需要初始化后重新启用 最近一次反复初始化后还是不能用

抱歉，更新了一次忘记回复，试试新的呢，我稳定使用了一周了

**Comment by christaikobo** [comment]
哈哈哈我也是发了之后看了一眼发现更新了
试了一下暂时没问题，多谢！
