### ISSUE TITLE
Dalamud 国服适配问题

### ISSUE THREAD

**Issue by pxDaydown** [Loskh/StarlightBreaker#9]
国服Dalamud中的StarlightBreaker已经失效很久了，一直没有更新，请问还有继续适配的打算吗？
![图片](https://user-images.githubusercontent.com/89113416/215482103-1dbc43fc-8317-4476-8e5a-6fa6ec33cbe9.png)

**Comment by Loskh** [comment]
上个月已经更新了，请点击垃圾桶图标删除后重新下载

**Comment by pxDaydown** [comment]
已解决，感谢作者大大。
